### ISSUE TITLE
Spam Sign ups - Make them stop

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#100]
Stop spam sign-ups.  
They are currently coming from @popdieta.pl

**Comment by NicoleLuxcentric** [comment]
Here is another one (same domain)

motitguco1981@popdieta.pl

**Comment by gtritchie** [comment]
Fixed by adding the ban-hammer plugin plus the code needed to integrate with Woocommerce.

To block new domains, go to Tools / Ban Hammer and add to the Blacklist.
