### ISSUE TITLE
Plugins that have been turned off - Need confirm

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#103]
I turned off and will phase out the following plugins
- WooCommerce chained products
- Follow-up Emails
- Sensei with WooCommerce Paid Courses
- Sensei LMS 

I may turn these back on someday
- Events Tickets plus
- The Events Calendar PRO

**Comment by gtritchie** [comment]
I tweaked the custom plugin and the luxcentric theme to remove Sensei-related code.
