### ISSUE TITLE
Upgrade API V1.0 to API V2.0 for Zoho

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#107]
Upgrade API V1  to API v2  - Expires 12/31/2019

Potential API Connections
Wordpress Plugins
- WooCommerce and Zoho CRM Connector Pro - Potent Plugin
- Custom Luxcentric Plugin

Zoho Flow to Calendly?

Forum Post Announcement
https://help.zoho.com/portal/community/topic/sunsetting-zoho-crm-api-version-1-0

Information from Zoho on API
https://www.zoho.com/crm/developer/docs/api/migration-v2.html

**Comment by NicoleLuxcentric** [comment]
Need Zoho CRM Access


https://help.zoho.com/portal/community/topic/migration-of-zoho-crm-apis-and-functions-to-v2-0

https://crm.zoho.com/crm/org37034097/settings/api/usage/graph-view

**Comment by NicoleLuxcentric** [comment]
Update information:
When trying to complete the authentication process for the new API from "WooCommerce and Zoho CRM Connector Pro" connection tab, get back this message:

Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

I found other discussions about this that specifically mention Bluehost, but nothing that has helped:

https://help.zoho.com/portal/community/topic/wordpress-zoho-plugin

https://stackoverflow.com/questions/28090737/not-acceptable-an-appropriate-representation-of-the-requested-resource-could-no

I also tried "Disable SSL certificate verification (not recommended)" and it did not help.

**Comment by NicoleLuxcentric** [comment]
Reset and received Message - Settings saved

**Comment by NicoleLuxcentric** [comment]
It is no longer giving me the error in the wordpress admin, but it is not doing the thing. 
I will create a test product to treoubleshoot.

**Comment by NicoleLuxcentric** [comment]
You can test the API on the testing page. Use the Free test product.

https://www.luxcentric.com/testing-gary/

If it works then a note should appear in the ZOHO CRM customer profile.  (See Marion Kyle)
![2020-01-05_12-32-52](https://user-images.githubusercontent.com/27643029/71785702-8c71a480-2fb7-11ea-958e-6533497d8c71.png)

**Comment by gtritchie** [comment]
Still unable to make this work. I disconnected Zoho CRM Connector Pro, deleted the Client ID from https://accounts.zoho.com/developerconsole, generated a new key, and connected again. It appears to be successful:

<img width="941" alt="2020-01-05_13-17-48" src="https://user-images.githubusercontent.com/10569626/71786214-c9d93080-2fbd-11ea-9f89-7ae7643b6bb9.png">


Then did a free purchase, and checked in Zoho and found no new notes.

I enabled Wordpress debugging and logging, and did this again, and didn't find anything related in the logs. I also tried with "Disable SSL certificate verification (not recommended)" checked but made no difference.

There is evidence that Zoho V2 API calls are coming through at the times I've been trying this:

<img width="446" alt="2020-01-05_13-19-59" src="https://user-images.githubusercontent.com/10569626/71786244-305e4e80-2fbe-11ea-92a6-897fb6a9356f.png">

**Comment by NicoleLuxcentric** [comment]
Potent PlugIn SOLUTION

From Jonathan at Potent Plugins
I was able to identify a couple issues that may be responsible for the symptoms you are seeing:
The Contact field "Email Lists" was problematic (the value was "Tech E-Rescue")
The Account field "Primary Contact" seemed to be problematic as well (the value was "[order_meta._billing_first_name] [order_meta._billing_last_name]")
I've removed both of these field values and order processing seems to be working again (at least from what I can see from the WordPress end). Once you've made any necessary corrections, you may want to re-submit orders to Zoho CRM for Contacts or Accounts where these fields are missing.

Regarding the "Email Lists" field, I am assuming this is a selection field of some sort? If so, is the value I mentioned available for selection in Zoho CRM (must match exactly, no space before or after, etc.)? If the value is present in Zoho CRM then I will need to do further investigation as to why it is causing problems when being sent over.

Regarding the "Primary Contact" field, I assume this is a contact selection field which means that Zoho is probably expecting a contact ID here instead of a name as was being provided. If you need a way to fill this in with the matching contact ID, let me know and we may be able to figure out a way to make it work.
