### ISSUE TITLE
Can I create custom shortcodes?

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#11]
Example:
At the bottom of my blogs, I want to put a call to action. I am currently pasting code to either encourage them to schedule a tech tackle or a strategy session or sign up to take the course. 

See 
https://www.luxcentric.com/passwords-passwords-passwords/?v=7516fd43adaa

as an example of the schedule a tech tackle one. (I don't really like how it looks but this is the basic idea)

**Comment by gtritchie** [comment]
The answer to the question "Can I create custom shortcodes?" is yes.

**Comment by NicoleLuxcentric** [comment]
Great thanks I will think on those :)
