### ISSUE TITLE
Testimonials slider too verbose with screen reader

### ISSUE THREAD

**Issue by gtritchie** [luxcentric/luxcentric#111]
We use Testimonials Widget Premium version 2.5.0, displayed in the footer sidebar via Testimonials Slider widget, where we fade between testimonials every 10 seconds.

With a screen reader running, each newly displayed testimonial gets announced; this is too verbose, making it extremely difficult if not impossible to use our site via screen reader.

To fix this, we need to be able to tell the bxSlider used by the Testimonials Slider to not set `aria-live="polite"`. BxSlider has a setting for this (`ariaLive`) which defaults to `true` but this is not exposed by the Testimonials Widget. It could easily be added in the same way some other low-level bxSlider properties are exposed such as `bxslider_adaptiveHeightSpeed`.

Note that we still want the ariaHidden bxSlider property to be set to true (also the default).

**Comment by NicoleLuxcentric** [comment]
Forwarded message to Axelerant

**Comment by NicoleLuxcentric** [comment]
they never responded except to discontinue existing.
