### ISSUE TITLE
The Wordpress Admin Bar is missing when logged into Wp-admin

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#113]
This bar used to appear when I was logged into my Admin Account for Luxcentric and looking at a live page. 

![2020-05-04_12-27-54](https://user-images.githubusercontent.com/27643029/81005370-b1a9de80-8e02-11ea-94be-5cb91502c8cf.png)

**Comment by gtritchie** [comment]
Fixed, was a problem with unbalanced element in popup plugin content.
