### ISSUE TITLE
Images not centering on website

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#119]
The new WordPress interface is not recognizing when I try to center an image.
On the game page

https://luxcentric.com/game/

All the game space images are in image placeholders in the colums and set to "center" according to WordPress, but they do not actually center on the page.
Same with the animated GIF at the bottom.

**Comment by gtritchie** [comment]
Investigation note: appears to be `display:block` overriding expected `display:table`.
