### ISSUE TITLE
Active courses progress bar different colors

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#14]
The progress bar on the active courses is a different color for the top one vs the bottom course. they should all be Salmon. It would be even better if they were Teal or Navy.

![image](https://cloud.githubusercontent.com/assets/27643029/26337764/149316da-3f30-11e7-931b-30dbda53a3c9.png)

**Comment by gtritchie** [comment]
Fixed. Needed css for [sensei_user_courses] shortcode progress meters.

Live on site: 2017-06-24 19:08

Change: e86656e

**Comment by gtritchie** [comment]
Confirmed fixed.
