### ISSUE TITLE
Workshop Ticket

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#15]
The "add to cart" button needs to be Branded.

![image](https://cloud.githubusercontent.com/assets/27643029/26517946/1e0bb574-4259-11e7-91f6-2729242ec625.png)

To repro, visit https://www.luxcentric.com/workshop/test-workshop
Note: This page is set to private in WordPress.

**Comment by gtritchie** [comment]
Fixed.
![2017-06-25_18-31-09](https://user-images.githubusercontent.com/10569626/27521690-7faa6a0e-59d4-11e7-9b15-089e5371b369.png)
