### ISSUE TITLE
Missing billing info prevents payment on membership upgrade

### ISSUE THREAD

**Issue by gtritchie** [luxcentric/luxcentric#16]
- As a logged-in user, go to test site (localhost:4040, using PayPal sandbox)
- Membership/Membership Info
- Membership Upgrade
- Select Options
- Add to cart (1 year)
- Get a checkout page, but billing details only has name and e-mail
![2017-06-03_18-18-39](https://cloud.githubusercontent.com/assets/10569626/26758098/64d80c92-4889-11e7-94ed-ac331f6c830e.png)
- Click on `Proceed to PayPal` button
- Get an error about missing billing info
![2017-06-03_18-22-13](https://cloud.githubusercontent.com/assets/10569626/26758104/96518b7c-4889-11e7-90e5-ea5cd54fe597.png)
- Have to go directly to shopping cart, then all info is shown and you can make payment

**Comment by gtritchie** [comment]
Fixed by removing code that caused a membership purchase to redirect to the checkout page instead of the cart. Now buying a membership behaves like any other purchase.

On site 2017-06-17 21:09

Change:  be8204a

**Comment by NicoleLuxcentric** [comment]
This issue seems to be happening when I try to buy something using the code: luxspecialfree
It used to work.

**Comment by gtritchie** [comment]
This issue now tracks the desire to not have users enter their billing information twice. Once in WooCommerce, and once again in PayPal.
