### ISSUE TITLE
pages print glitchie

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#17]
When I try to print a web page the pages print glitchie. (with background code printing) See attached PDF for example.
[Luxcentric Home.pdf](https://github.com/luxcentric/luxcentric/files/1068860/Luxcentric.Home.pdf)

**Comment by gtritchie** [comment]
Calling this fixed. This is something that doesn't work well on most web pages. I did change it so the links don't show the codes when printed.

Live on site: 2017-06-20

Change: dc08923da4cd96c7480966a59221e1a6e2d414ce
