### ISSUE TITLE
testimonials page

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#20]
Not sure when it changed :/ T the page used to have cute little frames around the profile pictures of people. It is not that way anymore. just plain boring pictures. 

Also, I want to be able to add testimonials with the cute framed profile on other pages. #

**Comment by gtritchie** [comment]
Fixed in css. The html generated by the plugin, probably due to an update, no longer matched the css. Put on site 06/15/2017 at 21:10.

Change: 24f7a30acb1592719db0d30caa8d50b95abb9b89
