### ISSUE TITLE
ugly gray border around "Add to Cart" button using short code

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#21]
I figured out how to add the "add to cart" button for products.
Use this shortcode for the Inbox Zero Gmail course. [add_to_cart id="3094"]
This example is on the Operation Inbox Zero product page.

https://www.luxcentric.com/product/operation-inbox-zero-ww-gm
Can the gray borderline be removed please?

![image](https://user-images.githubusercontent.com/27643029/27194861-14c9ab82-51b9-11e7-9450-38ff5606fdc4.png)

**Comment by gtritchie** [comment]
Fixed with css change. On live site on 2017-06-17 18:34.

Change:  e45ecb0
