### ISSUE TITLE
Add the ability to use Testimonials Short codes

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#24]
Add the ability to add shortcodes with the styling as shown on the testimonial page.
www.luxcentric.com/testimonials

Short code example (to add Alicia's Testimonial to a page)
[testimonials ids="2541" paging=false]

**Comment by gtritchie** [comment]
Fixed with css changes. Live on site at 2017-06-17 at 17:47.

Change: ba85481e

**Comment by NicoleLuxcentric** [comment]
Please set the widget short code to align left.

**Comment by gtritchie** [comment]
Left-justified testimonial text. Didn't change how name of person is displayed.

On live site: 2017-06-18 13:21
Change:  032cdb4
