### ISSUE TITLE
Odd email being sent

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#25]
When someone signs up for Operation: Inbox Zero for Gmail course they automatically receive an On the Path Membership. 
the receive several emails
1. Your account on Luxcentric - comes from Woocommerce Default Emails (works well)
2. Luxcentric Order Receipt for Inbox Zero Course - comes from Woocommerce Default Emails (works well)

THE PROBLEM
3. Welcome to Luxcentric: - I don't know where this one comes from, but I think I created it. It generates weird code and seems to be triggered by joining the on the path membership. I don't want this one to go out at all. And am curious where it comes from.
![image](https://user-images.githubusercontent.com/27643029/27265357-02765fa6-5449-11e7-9f3d-572bf9bdc41d.png)

![image](https://user-images.githubusercontent.com/27643029/27265362-1e35db18-5449-11e7-9b4e-1bc3ef586ca0.png)

4. Welcome to Operation: Inbox Zero for Gmail - comes from Follow Ups (works well)

**Comment by gtritchie** [comment]
You found it in Follow-Ups/Emails/WC Memberships.
