### ISSUE TITLE
Woocommerce shortcodes inconsistant

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#27]
I entered the following shortcodes on a test page and they are all for the same product to display differently. The middle ones for using product ID either don't show up or show up with the wrong product. Is this something Woocommerce needs to fix?

<strong>Add to cart for product #3094 Inbox Zero - Gmail</strong>
[add_to_cart id="3094"]
<hr>
<strong>Product ID for product #3094 Inbox Zero - Gmail</strong>
[product ids="3094"]
<hr>
<strong>Product ID for product #3094 Inbox Zero - Gmail</strong>
[product id="3094"]
<hr>
<strong>
Product page for product #3094 Inbox Zero - Gmail</strong>
[product_page id="3094"]
to see the example visit: https://www.luxcentric.com/errors/

![image](https://user-images.githubusercontent.com/27643029/27404072-97bf5f9c-5681-11e7-8a94-96f8729d033e.png)

Here is the documentation for the Woocommerce shortcodes I am using
https://docs.woocommerce.com/document/woocommerce-shortcodes/

**Comment by gtritchie** [comment]
The product won't show up in the [product id] tag unless Catalog Visibility is set to `Shop only` or `Shop and search results.`

Also, the plural tag form is [products ids="..."] (plural on both `products` and `ids`.
