### ISSUE TITLE
Aaahhhhhh Member Discount image is inconsistant

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#28]
The member discount image works perfectly on the Inbox Zero VIP program for "On the Path" members.

but the Tech Tackle discount is not showing the image
Note: the discount for the tech tackle is calculated in the cart page.

**Comment by NicoleLuxcentric** [comment]
and now it is working - I will keep an eye on it.

**Comment by NicoleLuxcentric** [comment]
It just seems odd. Something is going on. 
from the Inbox zero course page If a member clicks on the VIP program, it goes to the page and the discount is highlighted
when they go to the Private Lesson tackle the discount is sometimes not highlighted and they appear to be logged out.
Weird. 

Here is a link to video of the problem.
https://www.dropbox.com/s/8k3m25thvq7aqf4/discount%20error.mp4?dl=0

Pages involved:
https://www.luxcentric.com/course/operation-inbox-zero-workshop-gmail/
https://www.luxcentric.com/product/inbox-zero-vip
http://www.luxcentric.com/product/topic-tackle/

**Comment by NicoleLuxcentric** [comment]
I think I might have fixed it. 

This code renders the page without the member discount image
<a href="http://www.luxcentric.com/product/topic-tackle" target="_blank"><img class="wp-image-1800 aligncenter" src="https://www.luxcentric.com/wp-content/uploads/2017/01/tech-tackle.svg" alt="" width="101" height="150" /></a>

This code keeps the member logged in and renders the page with the member discount image
<a href="https://www.luxcentric.com/product/topic-tackle/" target="_blank" rel="noopener noreferrer"><img class="wp-image-1800 aligncenter" src="https://www.luxcentric.com/wp-content/uploads/2017/01/tech-tackle.svg" alt="" width="101" height="150" /></a>

I think this [rel="noopener noreferrer"] bit is important but I don't understand what it does.

**Comment by gtritchie** [comment]
Can't see the code, only the actual images. To put code example in a GitHub issue, put triple backticks on separate line before and after the code. Optional, specify it as HTML for automatic highlighting. See this page:

https://help.github.com/articles/creating-and-highlighting-code-blocks/

Here's an example:

\```html
\<b>This is some html</b>
\<a href="https://www.luxcentric.com">visit Luxcentric</a>
\```

looks like:

```html
<b>This is some html</b>
<a href="https://www.luxcentric.com">visit Luxcentric</a>
```

**Comment by NicoleLuxcentric** [comment]
Thanks :) I don't have the old code that doesn't work any more, but the good code is here:
```
<a href="https://www.luxcentric.com/product/topic-tackle/" target="_blank" rel="noopener noreferrer"><img class="wp-image-1800 aligncenter" src="https://www.luxcentric.com/wp-content/uploads/2017/01/tech-tackle.svg" alt="" width="101" height="150" /></a>
```

**Comment by NicoleLuxcentric** [comment]
I think we can consider this closed.
