### ISSUE TITLE
Image with Caption - please set background to be transparent

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#29]
Example on this page
https://www.luxcentric.com/course/operation-inbox-zero-workshop-gmail/

![image](https://user-images.githubusercontent.com/27643029/27458277-0df58958-575d-11e7-9ac6-4afc461ffb97.png)

This light gray background shows up when I add a caption to an image from my media.
I would like the gray background to be transparent so I have no background color behind these media links.

**Comment by gtritchie** [comment]
Fixed by c7b8d6f.

Live on site 2017-07-08 13:59

**Comment by NicoleLuxcentric** [comment]
perfection
