### ISSUE TITLE
Fix Unsubscribe page

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#31]
From the "My Account" Page. Members can manage their email subscriptions.
the manage subscriptions page is wonky and has an event calendar on it and is left justified too much.
![image](https://user-images.githubusercontent.com/27643029/27756967-28008f82-5db1-11e7-8829-c3c3b315b748.png)

https://www.luxcentric.com/email-preferences 

This may be using a Luxcentric page template, but it doesn't seem to be a "real" page.

**Comment by gtritchie** [comment]
For now I have removed the link, via Follow-Up Emails/Settings/Subscribers "Allow customers to manage their email list preferences from their account"

**Comment by NicoleLuxcentric** [comment]
thanks:
GOAL FOR SOMEDAY (you already know most of this)
I would like to use follow-ups to send newsletters to my "list" 
My list contains people who: 
Signed up for just the emails - not the website membership or products
Free Website Members
Paid Customers

Currently, I have it set up that everyone who purchases something or signs up for a membership is added to the Tech E-Training newsletter.

Currently, the Tech E-Training newsletter is hosted and sent by Zoho and not linked to my site.

**Comment by NicoleLuxcentric** [comment]
GOAL FOR SOMEDAY (you already know most of this)
I would like to use follow-ups to send newsletters to my "list" (Tech E-Training newsletter)
My list contains people who: 
Signed up for just the emails - not the website membership or products
Free Website Members
Paid Customers

Currently, the Tech E-Training newsletter is hosted and sent by Zoho and not linked to my site.

Currently, Follow-ups is being used for sending emails based on activities on the site. Follow-ups calls these types of emails "non-order emails".

It would be nice to have manage subscriptions for both Zoho and Follow-ups

**Comment by gtritchie** [comment]
I've made the built-in Follow-up emails pages look more reasonable (no calendar, standard margins). Functionality is still whatever the follow-up emails plugin is doing.

* https://luxcentric.com/unsubscribe
* https://luxcentric.com/email-subscriptions

Please open separate issues for:
* integrating Zoho
* adding an indication that unsubscribe was successful
* creating shortcode(s) so you can assemble your own pages to replace these

Each of these is large enough to track separately, I think?
