### ISSUE TITLE
Weird Event Code

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#33]
This weird code is sent with emails about the activity on the site. I don't know where it is coming from. I think it has to do with Sensei. In Sensi settings --> Woocommerce there is an option for 

```
Enable Sensei WooCommerce Integration Debugging	  Advanced: Log Sensei/WooCommerce integration events (Uses WC_Logger, logs events at `notice` level) 
```
It could also have to do with the Modern Tribe plug in that manages workshops and events.

![image](https://user-images.githubusercontent.com/27643029/27807581-a1adff94-5ff6-11e7-904b-bc30c83a4a44.png)

**Comment by gtritchie** [comment]
This is a bug in event-tickets-plus plugin. Until they fix it, I have made my own fix as described here:

https://theeventscalendar.com/support/forums/topic/missing-argument-2-for-tribe__tickets_plus__commerce__woocommerce__mainmaybe_a/

If the plug-in gets updated it will wipe out my fix, so I will keep an eye on it and either reapply my fix when I update, or wait until they officially fix it.
