### ISSUE TITLE
I want to create bullet points

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#34]
I have a code class where I can add bullet points in a list as cute little checkmarks. This is great, but I am not able to create simple bullet points like I would use in this post.

https://www.luxcentric.com/the-rhythm-of-a-good-task-list-part-1/

![image](https://user-images.githubusercontent.com/27643029/27810375-465e5db0-600e-11e7-864c-bd6c140d7e82.png)

I can do it on some parts of my site but not in the blog.

Works on this page
https://www.luxcentric.com/presentations/

![image](https://user-images.githubusercontent.com/27643029/27810392-89519a4c-600e-11e7-9499-49478b77ccf8.png)

**Comment by gtritchie** [comment]
As discussed, add class="disc", here's an example:
```
<ul class="disc">
 	<li>this is first item</li>
 	<li>second item</li>
</ul>
```
