### ISSUE TITLE
Member sign in page shows 2 log in sections

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#4]
Goal: One log-in section on the page and when someone is logged in they can see their account information and the courses they are taking. 
Problem: 2 log-in options showing
![image](https://cloud.githubusercontent.com/assets/27643029/25074117/8df862da-22a9-11e7-93c9-9203731caaf8.png)

Repo/Cause
Caused by 2 shortcodes on the page that require log-in to access
1. See page https://www.luxcentric.com/my-account/

both shortcodes seem to be needed to show account information and current courses.
1. When signed in - (see Test account Marion Kyle - Lastpass)

![image](https://cloud.githubusercontent.com/assets/27643029/25074160/2724d718-22aa-11e7-99e1-bf7cb07534ca.png)

**Comment by gtritchie** [comment]
Fixed by creating a Luxcentric plugin to add a `luxcentric_user_courses` shortcode. This is used in place of `[woocommerce_my_account]` and `[sensei_user_courses]`, and shows both if user is logged in, or just `woocommerce_my_account` if user is not logged in.
