### ISSUE TITLE
Unsubscribe - Success Indicator

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#40]
This may or may not be different based on the issue: Manage Unsubscribe Page - Stage 1
-------
For the non-order follow ups emails. from the follow ups plugin.

Please link successful unsubscribe action to a page that shows what they have successfully unsubscribed.

In other words, when they click unsubscribe from https://www.luxcentric.com/unsubscribe, to to the Unsubscribe Successful page: https://www.luxcentric.com/unsubscribe-success/

Eventually, I would also like the Zoho unsubscribes from Tech E-Training to go to this page as well.
See Email list wiki for how email subscriptions are organized.

**Comment by gtritchie** [comment]
After a successful unsubscribe it now redirects to the unsubscribe-success page. The checkbox is also checked automatically so you can just click the unsubscribe button.
