### ISSUE TITLE
Tech E-Training Subscribe - Weird Gap

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#42]
Here is the page with the problem:
https://www.luxcentric.com/tech-e-training-subscribe/

I used the embed code from Zoho Campaigns for the form to sign up for Tech E-Training.
There were a variety of problems with the code. I was able to solve some of them but I can't figure out how to get rid of the gap between where the page information ends and the form begins.

![weird gap](https://user-images.githubusercontent.com/27643029/28697666-6cde9eea-72f2-11e7-8868-fdd37c34dba3.png)

I will need to update this form from time to time so I will also need instructions on how to fix it in the future.

The original form is found in Zoho Campaigns.
Go to "List Management"
Choose "Tech E-Training - Special Bonus" 
Choose "Sign up Forms"
Choose "Tech E-Training - Luxcentric.com"

**Comment by gtritchie** [comment]
Some of the weird gap comes from <br> tags that the Wordpress editor puts in between the script tags. To fix, in the text editor put all the script elements on the same line by going to the start of each element and hitting backspace.

**before**
```
<!--Zoho Web-Optin Form Starts Here-->`
<script type="text/javascript" src="https://campaigns.zoho.com/js/jquery-1.11.0.min.js"></script><script type='text/javascript' src='https://campaigns.zoho.com/js/jquery-migrate-1.2.1.min.js'></script>
<script type='text/javascript' src='https://campaigns.zoho.com/js/jquery-ui-1.10.4.custom.min.js'></script>
<script type="text/javascript" src='https://campaigns.zoho.com/js/ui.datepicker.js' charset="utf-8"></script>
<script type="text/javascript" src="https://campaigns.zoho.com/js/jquery.form.js"></script>
<script type="text/javascript" src="https://campaigns.zoho.com/js/optin_min.js"></script><script type="text/javascript">
```

**after**:
```
<!--Zoho Web-Optin Form Starts Here-->
<script type="text/javascript" src="https://campaigns.zoho.com/js/jquery-1.11.0.min.js"></script><script type='text/javascript' src='https://campaigns.zoho.com/js/jquery-migrate-1.2.1.min.js'></script><script type='text/javascript' src='https://campaigns.zoho.com/js/jquery-ui-1.10.4.custom.min.js'></script><script type="text/javascript" src='https://campaigns.zoho.com/js/ui.datepicker.js' charset="utf-8"></script><script type="text/javascript" src="https://campaigns.zoho.com/js/jquery.form.js"></script><script type="text/javascript" src="https://campaigns.zoho.com/js/optin_min.js"></script><script type="text/javascript">
```

**Comment by gtritchie** [comment]
Got rid of more weird gap by adding `margin: 0;` in the paragraph right after the `<h2>`.

**before**
```
<p style="text-align: center;">
```
**after**
```
<p style="text-align: center; margin: 0;">
```

**Comment by gtritchie** [comment]
For the `*` after Contact Email, change from
```
<div style="width: 130px; float: left; margin-top: 5px; margin-right: 5px; text-align: left; font-size: 12px; font-family: Helvetica; color: #444444;">

Contact Email

<span style="color: #b40000; font-size: 11px; font-family: Arial;">*</span>

</div>
```
to:
```
<div style="width: 130px; float: left; margin-top: 5px; margin-right: 5px; text-align: left; font-size: 12px; font-family: Helvetica; color: #444444;">Contact Email <span style="color: #b40000; font-size: 11px; font-family: Arial;">*</span></div>
```
**Leave a space after `Contact Email`**.

**Comment by gtritchie** [comment]
![2017-08-06_15-31-20](https://user-images.githubusercontent.com/10569626/29007640-82142eb6-7abc-11e7-9f19-dbfd2c82e8d0.png)

**Comment by NicoleLuxcentric** [comment]
Yay :)
