### ISSUE TITLE
UpdraftPlus warns about extra whitespace

### ISSUE THREAD

**Issue by gtritchie** [luxcentric/luxcentric#5]
On UpdraftPlus existing backups tab, there is a warning about extra whitespace. There are suggestions about eliminating this warning at: https://updraftplus.com/problems-with-extra-white-space/

![image](https://cloud.githubusercontent.com/assets/10569626/25114146/48e35a3e-23b1-11e7-9bcd-d030a6d49282.png)

**Comment by gtritchie** [comment]
Fixed with change https://github.com/luxcentric/luxcentric/commit/22e41adc7adf9f2a1c225b17fd363dcc66cb5b4a.

There was extra whitespace at the start of bones.php. Warning should now be gone in UpdraftPlus exiting backup tab.

**Comment by NicoleLuxcentric** [comment]
Looks good :)
