### ISSUE TITLE
Course videos too small

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#6]
On the course page, I would like the video to span the width of the page and still maintain its responsive design, instead of just the upper left corner.
But if it affects quality too much, then we don't want to bother.

Example of how it is now.
![image](https://cloud.githubusercontent.com/assets/27643029/25411709/17daaa82-29d3-11e7-8eb6-2bc51c112c19.png)

**Comment by gtritchie** [comment]
You can make a video fill the width of the page by enclosing the YouTube embed code in:

**`<div class="videoResize">`**`<iframe ...></iframe>`**`</div>`**

Live on site: 2017/06/25 18:00

Change: 1431b9e

**Comment by NicoleLuxcentric** [comment]
thanks :)

**Comment by NicoleLuxcentric** [comment]
The video size on my online courses is no longer large. I think the style tag is no longer working.

Example: https://www.luxcentric.com/lesson/inbox-zero-initiation-1/

**Comment by gtritchie** [comment]
Irrelevant due to removal of Sensei
