### ISSUE TITLE
NEW Shortcode for those who ARE signed in (past issue = Sign in Sentence)

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#60]
If someone is already signed in to Luxcentric and they click the Registration button on the
https://www.luxcentric.com/membership-info/ page. They are taken to the https://www.luxcentric.com/registration/ page and it shows their account and the sentence 
"If you are already registered or have a membership, SIGN IN here." shows at the bottom.

![image](https://user-images.githubusercontent.com/27643029/29473021-f121a9f8-840a-11e7-9042-aa1b50ca407a.png)

This sentence is important for this page if they are NOT signed in, but odd if they ARE signed in.

**Comment by gtritchie** [comment]
Fixed.

Related change: dd4bb81

**Comment by NicoleLuxcentric** [comment]
Can I get another short code for those who ARE signed in?

```[lx_signed_in]Operation: INBOX ZERO Initiation  <span class="xsmall-btn"><a href="/course/operation-inbox-zero-strategy-course/" target="_blank">START THE COURSE</a></SPAN> [/lx_signed_in]```

**Comment by gtritchie** [comment]
Done.
