### ISSUE TITLE
Weird List formating

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#61]
See weirdness at https://www.luxcentric.com/membership-info/
When the window is stretched large it makes 2 columns but the Checklists get wonky.
Using woocommerce shortcode on this page.

![image](https://user-images.githubusercontent.com/27643029/29490523-e436958e-84f3-11e7-8649-7cc0f3b8b6f5.png)

The code for these memberships are in the "Short Description" section of products:
https://www.luxcentric.com/product/vip-beta-group/
and 
https://www.luxcentric.com/product/path-membership/

The checklists do just fine on the product pages.

**Comment by gtritchie** [comment]
Fixed.

Related change: a7fb343
