### ISSUE TITLE
Turn off "related products"

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#62]
Under various products Woocommerce adds a "Related Products" section below. I don't want those to show up any more.

See Examples: (almost any product page will show it - it is based on category)
https://www.luxcentric.com/product/operation-inbox-zero-gm/
https://www.luxcentric.com/product/tech-tackle/

**Comment by gtritchie** [comment]
I turned off "Related Products" for Woocommerce. Had to be done in code, no user setting.

For "You may also like..." you can control this on a per-product basis. When I turned this off on my test site for a product, it took a minute or two to take effect (or maybe I forgot to click Update the first time, not sure), but it did eventually work.

For example:

![2017-08-20_20-29-31](https://user-images.githubusercontent.com/10569626/29502637-50bd0c04-85e6-11e7-9023-57e88c850d30.png)
