### ISSUE TITLE
limit blog post width

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#64]
I don't like the margins on my blog post articles so close to the edge of the browser. 

I think a max of 600 or 700 would be good.

**Comment by gtritchie** [comment]
Adjusted.

**Comment by gtritchie** [comment]
Had to back out change for 75% as it messed up layout on About page. Needs further investigation.

**Comment by NicoleLuxcentric** [comment]
We don't need to bother with this.
