### ISSUE TITLE
Nested Lists

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#69]
In creating nested lists I want the choice to do a checklist, disc or nothing.
When I create a list with the checklist style (1st example)  it overrides the nested list. The disc style (2nd example) seems to work the way I want it to.

![2017-09-15_16-43-39](https://user-images.githubusercontent.com/27643029/30506965-08d6fa40-9a35-11e7-9556-c0253a658417.png)

```<ul class="checklist">
 	<li>For this lesson, you will need the <a href="https://drive.google.com/open?id=0B4gscbbpBJQFWFp3aG93SkNlaDQ" target="_blank" rel="noopener"><strong>Operation: Inbox Zero Initiation Handout</strong></a>.</li>
 	<li>Go through your email and ask yourself the questions and take action: 
<ul>
<li>Move emails to your !IN-Process folder</li>
<li>Move emails to your Save folders</li>
<li>Delete Email</li></ul>
 	<li>Go to your <strong>!In-Process Folder</strong> and do some work!</li>
</ul>
```

![2017-09-15_16-44-52](https://user-images.githubusercontent.com/27643029/30506979-34654fb8-9a35-11e7-94e9-cc441173d13d.png)

```
<ul class="disc">
 	<li>For this lesson, you will need the <a href="https://drive.google.com/open?id=0B4gscbbpBJQFWFp3aG93SkNlaDQ" target="_blank" rel="noopener"><strong>Operation: Inbox Zero Initiation Handout</strong></a>.</li>
 	<li>Go through your email and ask yourself the questions and take action: 
<ul>
<li>Move emails to your !IN-Process folder</li>
<li>Move emails to your Save folders</li>
<li>Delete Email</li></ul>
 	<li>Go to your <strong>!In-Process Folder</strong> and do some work!</li>
</ul>
```
Example taken from page: https://www.luxcentric.com/lesson/inbox-zero-initiation-4/

**Comment by gtritchie** [comment]
Fixed, should now work if a <ul class=disc> is nested inside a list item of a checklist list. I updated the source for this lesson.
