### ISSUE TITLE
Google Analytics - Plugin eval

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#77]
They say I need Google Analytics on my website. Google Analytics says the I need to paste code on to each page of my site (Like Zoho Did). I think Google Analytics does basicly the same thing as Zoho Sales IQ, but it is more recognized and I figure it won't hurt to have both. In my research to install they mention a plugin.  Here is the most useful article I found.
http://www.wpbeginner.com/beginners-guide/how-to-install-google-analytics-in-wordpress/
(Check out option 3)
I gave you analytics access with you gary@luxcentric.com email account.

**Comment by gtritchie** [comment]
Implemented with  5c6af5934f367deaa2e809758ae401108dd7ab92.
