### ISSUE TITLE
Text Alignment on Color Block

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#79]
https://www.luxcentric.com/product/brain-access
I have a color block and the letters are smashed against the edge I would like some clearance between edge and letters.

![image](https://user-images.githubusercontent.com/27643029/33967715-8260498c-e019-11e7-81fe-0eb397af383e.png)

**Comment by gtritchie** [comment]
The [row] shortcode was hardcoded to have padding of `"1em 0"` meaning 1em padding on top and bottom, and zero on left and right.

I changed row shortcut so you can specify the padding, for example this would make it 1em padding on all four sides:

`[row bgcolor="#00657e" padding="1em"]`

You can use any valid css units, including "px" for pixels.

The padding property can have 1 to 4 values.

- `padding=5px` means 5px padding on all sides.
- `padding=5px 3px` means 5px top and bottom, 3px left and right
- `padding=5px 3px 2px` means top is 5px, right and left are 3px, and bottom is 2px
- `padding=5px 3px 2px 1px` means 5=top, 3=right, 2=bottom, 1=left
