### ISSUE TITLE
Small-white-button needs update

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#8]
Class ="Small-White-Button" should be the same as Class="Small-Button" except with White letters for use on dark backgrounds. It currently shows as a Salmon Button see page

![image](https://cloud.githubusercontent.com/assets/27643029/26133716/19614a64-3a5e-11e7-8e0a-c487c0209fa7.png)
from page:
https://www.luxcentric.com/lesson/inbox-zero-workshop-lesson-1

It should be more like the Read More button on the button, but in white.
![image](https://cloud.githubusercontent.com/assets/27643029/26133746/61dce488-3a5e-11e7-816a-f200904dcb35.png)

**Comment by gtritchie** [comment]
Fixed via change bec4607dc353b72a80bc3a7d338628a53aa943a6.
