### ISSUE TITLE
Membership WP Editing page wonky

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#85]
I think something broke with the Woocommerce Membership plugin after the last update. The back end page where I can edit membership settings is wonky.

The places I should be able to edit fall off the grid.

https://www.luxcentric.com/wp-admin/post.php?post=3182&action=edit

![2018-07-10_16-09-42](https://user-images.githubusercontent.com/27643029/42542389-95da9594-845b-11e8-87d0-af04e4e74e82.png)

**Comment by gtritchie** [comment]
Should be better now. Fixed by updating plugins.
