### ISSUE TITLE
Odd Schedule Button in Quiz page on courses

### ISSUE THREAD

**Issue by NicoleLuxcentric** [luxcentric/luxcentric#9]
The Schedule button looks odd on the quiz page of a lesson.
Example
![image](https://cloud.githubusercontent.com/assets/27643029/26134144/5deff240-3a61-11e7-8337-18b6f15b478c.png)
on page: https://www.luxcentric.com/quiz/inbox-zero-workshop-lesson-1

Should be 
![image](https://cloud.githubusercontent.com/assets/27643029/26134169/878f2cd8-3a61-11e7-8d4d-9e0728f1a84a.png)
Like on page: 
https://www.luxcentric.com/lesson/inbox-zero-workshop-lesson-1/?v=7516fd43adaa

**Comment by gtritchie** [comment]
Fixed via stylesheet change.

Live on site 2017/06/22 22:25

Change: 59e1ec8

**Comment by gtritchie** [comment]
Nicole declares it "all better."

**Comment by gtritchie** [comment]
Confirmed fixed.
